export interface dataQuery {
  numeroPiso: 'estado_camas_live.piso'
  ejex: 'estado_camas_live.ejex'
  edificio: 'estado_camas_live.edificio2'
  ejey: 'estado_camas_live.ejey'
  estadoCama: 'estado_camas_live.estadocama' //
  apellidomaterno: 'estado_camas_live.apellidomaterno'
  apellidopaterno: 'estado_camas_live.apellidopaterno'
  apellidospaciente: 'estado_camas_live.apellidospaciente'
  ayuda_espiritual: 'estado_camas_live.ayuda_espiritual'
  cant_vacunas: 'estado_camas_live.cant_vacunas'
  cod_ccosto: 'estado_camas_live.cod_ccosto'
  cohorte: 'estado_camas_live.cohorte'
  cohortepcio: 'estado_camas_live.cohortepcio'
  cohorteugcc: 'estado_camas_live.cohorteugcc'
  departamento_medico_encuentros: 'estado_camas_live.departamento_medico_encuentros'
  desc_comuna: 'estado_camas_live.desc_comuna'
  desc_prevision: 'estado_camas_live.desc_prevision'
  desc_prevision_gestion: 'estado_camas_live.desc_prevision_gestion'
  desccama: 'estado_camas_live.desccama'
  desccama_original: 'estado_camas_live.desccama_original'
  edad: 'estado_camas_live.edad'
  es_funcionario: 'estado_camas_live.es_funcionario'
  estadia_pabellon: 'estado_camas_live.estadia_pabellon'
  grupo_religioso: 'estado_camas_live.grupo_religioso'
  grupo_unidad: 'estado_camas_live.grupo_unidad'
  incompatibilidad_religion: 'estado_camas_live.incompatibilidad_religion'
  incompatibilidad_religion_desc: 'estado_camas_live.incompatibilidad_religion_desc'
  ind_covid: 'estado_camas_live.ind_covid'
  indva_descripcion: 'estado_camas_live.indva_descripcion'
  medi_departamento: 'estado_camas_live.medi_departamento'
  medicotratantepaciente: 'estado_camas_live.medicotratantepaciente'
  motivohospitalizacionpaciente: 'estado_camas_live.motivohospitalizacionpaciente'
  naricera: 'estado_camas_live.naricera'
  nombre_medico_encuentros: 'estado_camas_live.nombre_medico_encuentros'
  nombrecompletopaciente: 'estado_camas_live.nombrecompletopaciente'
  nombrepaciente: 'estado_camas_live.nombrepaciente'
  otra_religion: 'estado_camas_live.otra_religion'
  ppn_paciente: 'estado_camas_live.ppn_paciente'
  practica_religion: 'estado_camas_live.practica_religion'
  religion: 'estado_camas_live.religion'
  rutpaciente: 'estado_camas_live.rutpaciente'
  secva_descripcion: 'estado_camas_live.secva_descripcion'
  servicio: 'estado_camas_live.servicio'
  tipo_aseo: 'estado_camas_live.tipo_aseo'
  tipo_prof: 'estado_camas_live.tipo_prof'
  tipo_unidad: 'estado_camas_live.tipo_unidad'
  ubicacion: 'estado_camas_live.ubicacion'
  unidad: 'estado_camas_live.unidad'
  unidad_temporal: 'estado_camas_live.unidad_temporal'
  valor_resultados: 'estado_camas_live.valor_resultados'
  ventmecinv: 'estado_camas_live.ventmecinv'
  ventmecnoinv: 'estado_camas_live.ventmecnoinv'
  vsrnu_episodio_id: 'estado_camas_live.vsrnu_episodio_id' //
  
  fecha_actualizacion_date: 'estado_camas_live.fecha_actualizacion_date'
  fecha_autorizacion_date: 'estado_camas_live.fecha_autorizacion_date'
  fecha_egreso_estimada_pabellon_date: 'estado_camas_live.fecha_egreso_estimada_pabellon_date'
  fecha_solicitud_date: 'estado_camas_live.fecha_solicitud_date'
  fechaaltaadmpaciente: 'estado_camas_live.fechaaltaadmpaciente_date'
  
  fechaaltamedicapaciente_date: 'estado_camas_live.fechaaltamedicapaciente_date'

  fechaaltaprobablepaciente_date: 'estado_camas_live.fechaaltaprobablepaciente_date'
  tiempoultimoestado2_date: 'estado_camas_live.tiempoultimoestado2_date'
  vsrda_fecha_ingreso_adm_date: 'estado_camas_live.vsrda_fecha_ingreso_adm_date'
}
export interface dataVitED {
  numeroPiso: 'estado_camas_live.piso'
  ejex: 'estado_camas_live.ejex'
  edificio: 'estado_camas_live.edificio2'
  ejey: 'estado_camas_live.ejey'
  estadoCama: 'estado_camas_live.estadocama' //
  apellidomaterno: 'estado_camas_live.apellidomaterno'
  apellidopaterno: 'estado_camas_live.apellidopaterno'
  apellidospaciente: 'estado_camas_live.apellidospaciente'
  ayuda_espiritual: 'estado_camas_live.ayuda_espiritual'
  cant_vacunas: 'estado_camas_live.cant_vacunas'
  cod_ccosto: 'estado_camas_live.cod_ccosto'
  cohorte: 'estado_camas_live.cohorte'
  cohortepcio: 'estado_camas_live.cohortepcio'
  cohorteugcc: 'estado_camas_live.cohorteugcc'
  departamento_medico_encuentros: 'estado_camas_live.departamento_medico_encuentros'
  desc_comuna: 'estado_camas_live.desc_comuna'
  desc_prevision: 'estado_camas_live.desc_prevision'
  desc_prevision_gestion: 'estado_camas_live.desc_prevision_gestion'
  desccama: 'estado_camas_live.desccama'
  desccama_original: 'estado_camas_live.desccama_original'
  edad: 'estado_camas_live.edad'
  es_funcionario: 'estado_camas_live.es_funcionario'
  estadia_pabellon: 'estado_camas_live.estadia_pabellon'
  grupo_religioso: 'estado_camas_live.grupo_religioso'
  grupo_unidad: 'estado_camas_live.grupo_unidad'
  incompatibilidad_religion: 'estado_camas_live.incompatibilidad_religion'
  incompatibilidad_religion_desc: 'estado_camas_live.incompatibilidad_religion_desc'
  ind_covid: 'estado_camas_live.ind_covid'
  indva_descripcion: 'estado_camas_live.indva_descripcion'
  medi_departamento: 'estado_camas_live.medi_departamento'
  medicotratantepaciente: 'estado_camas_live.medicotratantepaciente'
  motivohospitalizacionpaciente: 'estado_camas_live.motivohospitalizacionpaciente'
  naricera: 'estado_camas_live.naricera'
  nombre_medico_encuentros: 'estado_camas_live.nombre_medico_encuentros'
  nombrecompletopaciente: 'estado_camas_live.nombrecompletopaciente'
  nombrepaciente: 'estado_camas_live.nombrepaciente'
  otra_religion: 'estado_camas_live.otra_religion'
  ppn_paciente: 'estado_camas_live.ppn_paciente'
  practica_religion: 'estado_camas_live.practica_religion'
  religion: 'estado_camas_live.religion'
  rutpaciente: 'estado_camas_live.rutpaciente'
  secva_descripcion: 'estado_camas_live.secva_descripcion'
  servicio: 'estado_camas_live.servicio'
  tipo_aseo: 'estado_camas_live.tipo_aseo'
  tipo_prof: 'estado_camas_live.tipo_prof'
  tipo_unidad: 'estado_camas_live.tipo_unidad'
  ubicacion: 'estado_camas_live.ubicacion'
  unidad: 'estado_camas_live.unidad'
  unidad_temporal: 'estado_camas_live.unidad_temporal'
  valor_resultados: 'estado_camas_live.valor_resultados'
  ventmecinv: 'estado_camas_live.ventmecinv'
  ventmecnoinv: 'estado_camas_live.ventmecnoinv'
  vsrnu_episodio_id: 'estado_camas_live.vsrnu_episodio_id' //
  
  fecha_actualizacion_date: 'estado_camas_live.fecha_actualizacion_date'
  fecha_autorizacion_date: 'estado_camas_live.fecha_autorizacion_date'
  fecha_egreso_estimada_pabellon_date: 'estado_camas_live.fecha_egreso_estimada_pabellon_date'
  fecha_solicitud_date: 'estado_camas_live.fecha_solicitud_date'
  fechaaltaadmpaciente: 'estado_camas_live.fechaaltaadmpaciente_date'
  
  fechaaltamedicapaciente_date: 'estado_camas_live.fechaaltamedicapaciente_date'

  fechaaltaprobablepaciente_date: 'estado_camas_live.fechaaltaprobablepaciente_date'
  tiempoultimoestado2_date: 'estado_camas_live.tiempoultimoestado2_date'
  vsrda_fecha_ingreso_adm_date: 'estado_camas_live.vsrda_fecha_ingreso_adm_date'
}
